
// // list of all models with corresponding info to display

export const modelData = [
    // {
    //     name: "Over-Ear Headphones",
    //     modelPath: "/3d_models/koss_porta_pro/scene.gltf",
    //     textContent: [
    //         "Trends in personal technology also doesn't necessarily abide by the near-linear pace of technical development — instead, it can cycle more like fashion. Again, like in the fashion industry, there is a sense that previous generations did it better, removing such devices from the typically starry-eyed vision of technology's ever-improving quality. The popularity of first the wired and subsequently the over-ear headphone is one example of this cycle in action.",
    //         "In 2021, after preferences had largely fallen in line with technical progress for years, wired headphones experienced a surge in popularity. This trend could be seen as a continuation of the broader Y2K movement, in which tech like tamagotchis and other gaming devices, digital cameras, and vintage headphones was a key component of the broader trend. The wired headphones were seen as an effortless indication of one's distance from the digital world.",
    //         "The subsequent shift from the wired headphone to the over ear represents another frequent fashion cycle from minimalist to maximalist silhouettes. The release and popularity of the chunky, ostentatious Apple Airpod Maxes represent this transition at the corporate level, as the device has become both a status symbol due to its hefty price tag and a key component of 'clean girl' aesthetics that revolve around a sense of perfectly-manicured simplicity. The Maxes, like many of Apple's products, serve as a blank canvas for customization through decorative charms, covers, and cases, but a parallel rise of the Koss Porta Pros suggests that the choice of the device itself without additional decorations is also a form of personal expression.",
    //         "The popularity of the Porta Pros represented a continuation of the wired headphone trend, providing a high-quality listening experience characteristic of over ear headphones while maintaining the affordable accessibility and distinctly retro aesthetic of the wired headphones. Unlike the maxes, these devices are themselves a personalization – they don't require any additional details other than their default 70s aesthetic to communicate their intended message.",
    //         "As accessories that interact with our physical bodies much as clothes do, headphones are one item of personal technology that acts more like an article of clothing than a piece of technology — the choice of the item itself communicates a message about its owner, following a model of pre-purchased uniqueness in contrast to other personalizations that require more modifications to the object itself.",
    //         "Like lovers of vinyl records or digital cameras, many over-ear headphone users accredit their choice to the devices' superior functionality, which also brings the message communicated by the device one layer deeper. Alluding to a sense of functionality portrays oneself as rational and passionate, perhaps alluding to the devices' owner's superior expertise — itself an impression caused by the choice to adorn oneself with a specific set."
    //     ],
    //     camPos: 1,
    //     light: 20,
    //     CS_camPos: 0.8,
    //     subtitle: "Personal technology as fashion, trend cycles and all",
    //     origin: 2000,
    //     primary_influences: ["gen z", "music"],
    // },
    {
        name: "TEST",
        modelPath: "/3d_models/output.glb",
        textContent: [
            "We identify ourselves not only through personal expression, but also through who we choose to associate with. When one choses to depict someone on their lock screen, this otherwise often unsaid dynamic is manifested as a physical indicator of one's most important connection.",
            "Intentional announcements of one's relationships, especially romantic ones, has been a key tradition for many, dating from the era of news paper ads. First translated to the digital world through features like Facebook's relationship status, symbols of our commitment to our significant other are a key step in the strictly-defined and oft-discussed prescribed path to romantic success. In this dynamic, the public nature of the announcement is key -- bringing the relationship from the uncertainty of a secret out for anyone to see holds both members accountable to their relationship's many witnesses.",
            "After use of the Facebooks relationship status has plummeted in the last 10 years, many users suggest that it was also this sense of publicness that prompted them to move away from the app's status update feature. Today, representing one's relationship through their lock screen continues to build on Facebook's digitization of the relationship status — while still the most public component of one's cell phone, the lock screen is theoretically accessible to anyone who might take only a passing glance toward a phone — reducing the directness of the status update while still clearly indicating that the relationship is no longer secret or private.",
            "The use of the cell phone in recording our most valued relationships also acknowledges that the phone has taken over the role of 'default' personal object from something like the wallet. Storing one's image in your wallet was previously high praise, with the wallet representing an object that is so necessary and often-used that placing an image inside it indicates a desire to keep constantly close with its subject. Now, this same sentiment is ascribed to the cell phone — with the average person checking their phone 58 times per day, the lock screen truly is one of the most prominent mediums we view.",
            "Inversely, our choice of where to display relationship announcements also reflects their immense personal value — in a wallet, the images of one's loved ones sit directly next to one's official IDs, suggesting that those people contribute to one's identity as much as their official status. Similarly, on Facebook, one's relationship status is displayed along with their profile, placing one's partner as an identifying trait just like a name or biography. Perhaps this pattern suggests that the cell phone has also increasingly become our form of identification [DIDN'T WE TALK ABOUT THIS IN CLASS], as it is the most accessible device through which we message, post, and document our digital lives."
        ],
        camPos: 1,
        light: 1,
        CS_camPos: 1,
        subtitle: "The Facebook relationship status update, modernized",
        origin: 2000,
        primary_influences: [],
    },
    {
        name: "Mobile Lock Screens",
        modelPath: "/3d_models/patty-lock-phone.glb",
        textContent: [
            "We identify ourselves not only through personal expression, but also through who we choose to associate with. When one choses to depict someone on their lock screen, this otherwise often unsaid dynamic is manifested as a physical indicator of one's most important connection.",
            "Intentional announcements of one's relationships, especially romantic ones, has been a key tradition for many, dating from the era of news paper ads. First translated to the digital world through features like Facebook's relationship status, symbols of our commitment to our significant other are a key step in the strictly-defined and oft-discussed prescribed path to romantic success. In this dynamic, the public nature of the announcement is key -- bringing the relationship from the uncertainty of a secret out for anyone to see holds both members accountable to their relationship's many witnesses.",
            "After use of the Facebooks relationship status has plummeted in the last 10 years, many users suggest that it was also this sense of publicness that prompted them to move away from the app's status update feature. Today, representing one's relationship through their lock screen continues to build on Facebook's digitization of the relationship status — while still the most public component of one's cell phone, the lock screen is theoretically accessible to anyone who might take only a passing glance toward a phone — reducing the directness of the status update while still clearly indicating that the relationship is no longer secret or private.",
            "The use of the cell phone in recording our most valued relationships also acknowledges that the phone has taken over the role of 'default' personal object from something like the wallet. Storing one's image in your wallet was previously high praise, with the wallet representing an object that is so necessary and often-used that placing an image inside it indicates a desire to keep constantly close with its subject. Now, this same sentiment is ascribed to the cell phone — with the average person checking their phone 58 times per day, the lock screen truly is one of the most prominent mediums we view.",
            "Inversely, our choice of where to display relationship announcements also reflects their immense personal value — in a wallet, the images of one's loved ones sit directly next to one's official IDs, suggesting that those people contribute to one's identity as much as their official status. Similarly, on Facebook, one's relationship status is displayed along with their profile, placing one's partner as an identifying trait just like a name or biography. Perhaps this pattern suggests that the cell phone has also increasingly become our form of identification [DIDN'T WE TALK ABOUT THIS IN CLASS], as it is the most accessible device through which we message, post, and document our digital lives."
        ],
        camPos: 1,
        light: 1,
        CS_camPos: 1,
        subtitle: "The Facebook relationship status update, modernized",
        origin: 2000,
        primary_influences: [],
    },
    {
        name: "Mechanical Keyboards",
        modelPath: "/3d_models/mechanical_keyboard_-_aesthetic/scene.glb",
        textContent: [
            "Personalizations aren't always visible. The rise of 'creamy' keyboards highlights an auditory characteristic that is uniquely communal – very few noises other than keyboard clicks are appropriate to hear from others in public – introducing a new sensory realm through which to express ourselves. Often built from foundational cases with infinitely-customizable keycaps, mechanical keyboards offer both visual and oral personalization.",
            "Elevating the keyboard click also incentivizes rapid typing to generate more of the desired sound. In this dimension, personalized creamy keyboards give productivity an aesthetic medium, as non-stop rapid typing becomes desirable not only to maximize work completed but also for one's auditory enjoyment.",
            "As well as perhaps motivating the keyboard's user to work more, the effervescent nature of keyboard noises also communicates a message to others that the keyboards' owner is performing efficiently. The dispersal of sound from such keyboards spreads their message to anyone nearby regardless of their intention to perceive the noise, serving as a constant communal reminder that the keyboard's owner is actively at work."
        ],
        camPos: 1,
        light: 1,
        CS_camPos: 1.1,
        subtitle: "The curation of a personal sound",
        origin: 2000,
        primary_influences: [],
    },
    {
        name: "Smart Watches",
        modelPath: "/3d_models/apple_watch_series_5/scene.gltf",
        textContent: [],
        camPos: 0.8,
        light: 1,
        CS_camPos: 0.8,
        subtitle: "",
        origin: 2000,
        primary_influences: [],
    },
    {
        name: "Cell Phone Accessories",
        modelPath: "/3d_models/phone-case.glb",
        textContent: [
            "The smart phone revolutionized the shape of our telephones not only through its functionality but also its lack thereof – the perceived fragility of the early glass-encased smartphone models accelerated an existing trend to create protective cases that reduced damage on the increasingly expensive devices.",
            "Today, however, phone cases have become a key opportunity for personalization – one can choose their case based on color, texture, included accessories, and, of course, on its protective functionality. However, radical improvements in reinforced glass technology and an increasing availability of flimsy, obviously useless cases has led to the cases' aesthetic role trumping its functionality.",
            "The constant prominence of the phone case may have been one contributing factor in this transition – while not everyone around you will have access to the phone's digital content, the back of the phone faces away from the user and towards their surroundings, making it the most exterior-facing aspect of the device. As cell phones have gained a status as an extension of one's personal space, the case becomes increasingly representative of its owner.",
            "In some ways, cell phone accessorization is not only no longer functional but also actively costs its user function at the behest of aesthetics. Sonny Angel dolls, for example, rose out of Japan's Kawaii movement and today adorn everything from bedroom shelves to phone and laptop screens. The 'hipper' doll, which adheres to shelf-like objects, quickly became a popular collector's item and frequently sits on top of one's phone screen. As many Reddit users describe, adding a hipper to your phone makes it harder to fit in pockets, bags, and one's own hands, but none suggest that this inconvenience was worth removing the doll. Instead, commenters suggested that 'the cuteness is worth all the trouble whenever a waitress or barista gushes over it' – highlighting the importance of such decoration for the direct purpose of communicating and connecting with others.",
            "Cell phones also communicate a message about their owner through a lack of personal adornment. A growing anti-case trend, for example, might suggest that the phone's owner simply doesn't care if their phone breaks as the cost to replace it is negligible. This trend is especially popular among those who express a goal to highlight the devices' 'beautiful hardware,' perhaps serving to communicate a sort of technical expertise — itself related to the financial stability needed to risk such an expensive item — through their comfort with their bare phones.",
            "Cell phone manufacturers might have another reason to want customers to add the case – Valente, an IPhone owner interviewed by the BBC, suggested that going caseless 'made me more conscious of the thing, and I find I don't get blindly sucked in as much as I used to. I can't believe I'm saying this but I think I'm actually using my phone less.' Perhaps the appeal of the case, making the phone personalized to each owners' precise needs – with stands, finger shelves, and grip texture – contributes to the ease with which the phone has come to act as an extension of our bodies."
        ],
        camPos: 1,
        light: 1,
        CS_camPos: 1,
        subtitle: "Aesthetics at the cost of functionality",
        origin: 2000,
        primary_influences: [],
    },
    {
        name: "Laptops",
        modelPath: "/3d_models/laptop-with-sticker.glb",
        textContent: [
            "Stickers communicate in- and out-group status, speaking only directly to those who recognize the reference they make. Long popular as an expression of our identity or presence, stickers have been placed on everything from luggage to public infrastructure to water bottles. Their popularity on laptops represents the extension of an existing physical trend into the world of personal devices, and is especially interesting considering where laptop stickers are often placed — on the back of the device, facing away from the device's owner and oriented toward those around them. This positioning highlights the stickers' primary role as communication to other, not self-identification.",
            "Our laptops themselves are also increasingly catering to the assumption that they will be decorated. Apple's pioneering use of a flat, sleek screen creates a sense of a blank page made to be filled, and represents a larger move on the part of many manufacturers toward the production of a blank page ripe with possibility instead of an attempt to produce the perfect version for each customer [CAN ADD MORE HERE ABOUT THIS IF DESIRED]."
        ],
        camPos: 1,
        light: 3,
        CS_camPos: 1,
        subtitle: "Stickers as cultural dog whistles",
        origin: 2000,
        primary_influences: [],
    },
    {
        name: "Nintendo Switches",
        modelPath: "/3d_models/nintendo_switch_2/scene.gltf",
        textContent: [],
        camPos: 1.2,
        light: 1,
        CS_camPos: 0.9,
        subtitle: "Engineering individuality",
        origin: 2000,
        primary_influences: [],
    },
    {
        name: "Mobile Home Screens",
        modelPath: "/3d_models/patty-home-phone.glb",
        textContent: [
            "Many personalizations are made to communicate a message to others, but the cell phone home screen is a space unlikely to be seen by many others. Despite this privacy, home screen organization has become an important expressive outlet for many. With a growing industry of highly-customizable digital organization tools that often pitch their necessity on a constant demand for optimization, home screen customization perhaps serves to as a self-affirmation of one's control and organization.",
            "Like intricately-designed Notion pages and the growing popularity (https://business.yougov.com/content/49901-scribbles-and-screens-a-look-at-the-evolving-stationery-market-in-the-uk) of highly-optimized stationary products, a well-organized home screen is a near-constant reminder of one's sense of control. As our lives are increasingly reflected through the digital platforms we access through our home screens, maintaining its pristine aesthetic might percolate this sense of calm and control to the overwhelming digital world beyond the home screen."
        ],
        camPos: 1,
        light: 1,
        CS_camPos: 1,
        subtitle: "Convincing ourselves of our own projections",
        origin: 2000,
        primary_influences: [],
    },
];

// export const modelData = [
//     {
//         name: "Over-Ear Headphones",
//         modelPath: "/3d_models/koss_porta_pro/scene.gltf",
//         textContent: "<div className={styles.para}>Trends in personal technology also doesn’t necessarily abide by the near-linear pace of technical development — instead, it can cycle more like fashion. Again, like in the fashion industry, there is a sense that previous generations did it better, removing such devices from the typically starry-eyed vision of technology’s ever-improving quality. The popularity of first the wired and subsequently the over-ear headphone is one example of this cycle in action.</div><div className={styles.para}>In 2021, after preferences had largely fallen in line with technical progress for years, wired headphones experienced a surge in popularity. This trend could be seen as a continuation of the broader Y2K movement, in which tech like tamagotchis and other gaming devices, digital cameras, and vintage headphones was a key component of the broader trend. The wired headphones were seen as an effortless indication of one’s distance from the digital world.</div><div className={styles.para}>The subsequent shift from the wired headphone to the over ear represents another frequent fashion cycle from minimalist to maximalist silhouettes. The release and popularity of the chunky, ostentatious Apple Airpod Maxes represent this transition at the corporate level, as the device has become both a status symbol due to its hefty price tag and a key component of ‘clean girl’ aesthetics that revolve around a sense of perfectly-manicured simplicity. The Maxes, like many of Apple’s products, serve as a blank canvas for customization through decorative charms, covers, and cases, but a parallel rise of the Koss Porta Pros suggests that the choice of the device itself without additional decorations is also a form of personal expression.</div> <div className={styles.para}>The popularity of the Porta Pros represented a continuation of the wired headphone trend, providing a high-quality listening experience characteristic of over ear headphones while maintaining the affordable accessibility and distinctly retro aesthetic of the wired headphones. Unlike the maxes, these devices are themselves a personalization – they don’t require any additional details other than their default 70s aesthetic to communicate their intended message. </div><div className={styles.para}>As accessories that interact with our physical bodies much as clothes do, headphones are one item of personal technology that acts more like an article of clothing than a piece of technology — the choice of the item itself communicates a message about its owner, following a model of pre-purchased uniqueness in contrast to other personalizations that require more modifications to the object itself.</div><div className={styles.para}>Like lovers of vinyl records or digital cameras, many over-ear headphone users accredit their choice to the devices’ superior functionality, which also brings the message communicated by the device one layer deeper. Alluding to a sense of functionality portrays oneself as rational and passionate, perhaps alluding to the devices’ owner’s superior expertise — itself an impression caused by the choice to adorn oneself with a specific set.</div>",
//         camPos: 1,
//         light: 20,
//         CS_camPos: 0.8,
//         subtitle: "Personal technology as fashion, trend cycles and all", // or something about changing our idea of technical imrpovement (ultimately it is still improving
//         origin: 2000,
//         primary_influences: ["gen z", "music"],
//     },
//     {
//         name: "Mobile Lock Screens",
//         modelPath: "/3d_models/patty-lock-phone.glb",
//         textContent: "<div className={styles.para}>We identify ourselves not only through personal expression, but also through who we choose to associate with. When one choses to depict someone on their lock screen, this otherwise often unsaid dynamic is manifested as a physical indicator of one’s most important connection.</div><div className={styles.para}>Intentional announcements of one’s relationships, especially romantic ones, has been a key tradition for many, dating from the era of news paper ads. First translated to the digital world through features like Facebook’s relationship status, symbols of our commitment to our significant other are a key step in the strictly-defined and oft-discussed prescribed path to romantic success. In this dynamic, the public nature of the announcement is key -- bringing the relationship from the uncertainty of a secret out for anyone to see holds both members accountable to their relationship’s many witnesses. </div><div className={styles.para}>After use of the Facebooks relationship status has plummeted in the last 10 years, many users suggest that it was also this sense of publicness that prompted them to move away from the app’s status update feature. Today, representing one’s relationship through their lock screen continues to build on Facebook’s digitization of the relationship status — while still the most public component of one’s cell phone, the lock screen is theoretically accessible to anyone who might take only a passing glance toward a phone — reducing the directness of the status update while still clearly indicating that the relationship is no longer secret or private. </div><div className={styles.para}>The use of the cell phone in recording our most valued relationships also acknowledges that the phone has taken over the role of “default” personal object from something like the wallet. Storing one’s image in your wallet was previously high praise, with the wallet representing an object that is so necessary and often-used that placing an image inside it indicates a desire to keep constantly close with its subject. Now, this same sentiment is ascribed to the cell phone — with the average person checking their phone 58 times per day, the lock screen truly is one of the most prominent mediums we view.  </div><div className={styles.para}>Inversely, our choice of where to display relationship announcements also reflects their immense personal value — in a wallet, the images of one’s loved ones sit directly next to one’s official IDs, suggesting that those people contribute to one’s identity as much as their official status. Similarly, on Facebook, one’s relationship status is displayed along with their profile, placing one’s partner as an identifying trait just like a name or biography. Perhaps this pattern suggests that the cell phone has also increasingly become our form of identification [DIDN”T WE TALK ABOUT THIS IN CLASS], as it is the most accessible device through which we message, post, and document our digital lives. </div>",
//         camPos: 1,
//         light: 1,
//         CS_camPos: 1,
//         subtitle: "The Facebook relationship status update, modernized",
//         origin: 2000,
//         primary_influences: [],
//     },
//     {
//         name: "Mechanical Keyboards",
//         modelPath: "/3d_models/mechanical_keyboard_-_aesthetic/scene.glb",
//         textContent: "<div className={styles.para}>Personalizations aren’t always visible. The rise of ‘creamy’ keyboards highlights an auditory characteristic that is uniquely communal – very few noises other than keyboard clicks are appropriate to hear from others in public – introducing a new sensory realm through which to express ourselves. Often built from foundational cases with infinitely-customizable keycaps, mechanical keyboards offer both visual and oral personalization.</div> <div className={styles.para}>Elevating the keyboard click also incentivizes rapid typing to generate more of the desired sound. In this dimension, personalized creamy keyboards give productivity an aesthetic medium, as non-stop rapid typing becomes desirable not only to maximize work completed but also for one’s auditory enjoyment. </div> <div className={styles.para}>As well as perhaps motivating the keyboard’s user to work more, the effervescent nature of keyboard noises also communicates a message to others that the keyboards’ owner is performing efficiently. The dispersal of sound from such keyboards spreads their message to anyone nearby regardless of their intention to perceive the noise, serving as a constant communal reminder that the keyboard’s owner is actively at work.</div> ",
//         camPos: 1,
//         light: 1,
//         CS_camPos: 1.1,
//         subtitle: "The curation of a personal sound",
//         origin: 2000,
//         primary_influences: [],
//     },
//     {
//         name: "Smart Watches",
//         modelPath: "/3d_models/apple_watch_series_5/scene.gltf",
//         textContent: "",
//         camPos: 0.8,
//         light: 1,
//         CS_camPos: 0.8,
//         subtitle: "",
//         origin: 2000,
//         primary_influences: [],
//     },
//     {
//         name: "Cell Phone Accessories",
//         modelPath: "/3d_models/phone-case.glb",
//         textContent: "<div className={styles.para}>The smart phone revolutionized the shape of our telephones not only through its functionality but also its lack thereof – the perceived fragility of the early glass-encased smartphone models accelerated an existing trend to create protective cases that reduced damage on the increasingly expensive devices. </div><div className={styles.para}>Today, however, phone cases have become a key opportunity for personalization – one can choose their case based on color, texture, included accessories, and, of course, on its protective functionality. However, radical improvements in reinforced glass technology and an increasing availability of flimsy, obviously useless cases has led to the cases’ aesthetic role trumping its functionality. </div><div className={styles.para}>The constant prominence of the phone case may have been one contributing factor in this transition – while not everyone around you will have access to the phone’s digital content, the back of the phone faces away from the user and towards their surroundings, making it the most exterior-facing aspect of the device. As cell phones have gained a status as an extension of one’s personal space, the case becomes increasingly representative of its owner.</div><div className={styles.para}>In some ways, cell phone accessorization is not only no longer functional but also actively costs its user function at the behest of aesthetics. Sonny Angel dolls, for example, rose out of Japan’s Kawaii movement and today adorn everything from bedroom shelves to phone and laptop screens. The ‘hipper’ doll, which adheres to shelf-like objects, quickly became a popular collector’s item and frequently sits on top of one’s phone screen. As many Reddit users describe, adding a hipper to your phone makes it harder to fit in pockets, bags, and one’s own hands, but none suggest that this inconvenience was worth removing the doll. Instead, commenters suggested that ‘the cuteness is worth all the trouble whenever a waitress or barista gushes over it’ – highlighting the importance of such decoration for the direct purpose of communicating and connecting with others. </div><div className={styles.para}>Cell phones also communicate a message about their owner through a lack of personal adornment. A growing anti-case trend, for example, might suggest that the phone’s owner simply doesn’t care if their phone breaks as the cost to replace it is negligible. This trend is especially popular among those who express a goal to highlight the devices’ ‘beautiful hardware,’ perhaps serving to communicate a sort of technical expertise — itself related to the financial stability needed to risk such an expensive item — through their comfort with their bare phones. </div><div className={styles.para}>Cell phone manufacturers might have another reason to want customers to add the case – Valente, an IPhone owner interviewed by the BBC, suggested that going caseless ‘made me more conscious of the thing, and I find I don't get blindly sucked in as much as I used to. I can't believe I'm saying this but I think I'm actually using my phone less.’ Perhaps the appeal of the case, making the phone personalized to each owners’ precise needs – with stands, finger shelves, and grip texture – contributes to the ease with which the phone has come to act as an extension of our bodies.</div>",
//         camPos: 1,
//         light: 1,
//         CS_camPos: 1,
//         subtitle: "Aesthetics at the cost of functionality",
//         origin: 2000,
//         primary_influences: [],
//     },
//     {
//         name: "Laptops",
//         modelPath: "/3d_models/laptop-with-sticker.glb",
//         textContent: "<div className={styles.para}>Stickers communicate in- and out-group status, speaking only directly to those who recognize the reference they make. Long popular as an expression of our identity or presence, stickers have been placed on everything from luggage to public infrastructure to water bottles. Their popularity on laptops represents the extension of an existing physical trend into the world of personal devices, and is especially interesting considering where laptop stickers are often placed — on the back of the device, facing away from the device’s owner and oriented toward those around them. This positioning highlights the stickers’ primary role as communication to other, not self-identification. </div><div className={styles.para}>Our laptops themselves are also increasingly catering to the assumption that they will be decorated. Apple’s pioneering use of a flat, sleek screen creates a sense of a blank page made to be filled, and represents a larger move on the part of many manufacturers toward the production of a blank page ripe with possibility instead of an attempt to produce the perfect version for each customer [CAN ADD MORE HERE ABOUT THIS IF DESIRED].</div>",
//         camPos: 1,
//         light: 3,
//         CS_camPos: 1,
//         subtitle: "Stickers as cultural dog whistles",
//         origin: 2000,
//         primary_influences: [],
//     },
//     {
//         name: "Nintendo Switches",
//         modelPath: "/3d_models/nintendo_switch_2/scene.gltf",
//         textContent: "",
//         camPos: 1.2,
//         light: 1,
//         CS_camPos: 0.9,
//         subtitle: "Engineering individuality",
//         origin: 2000,
//         primary_influences: [],
//     },
    
//     {
//         name: "Mobile Home Screens",
//         modelPath: "/3d_models/patty-home-phone.glb",
//         textContent: "<div className={styles.para}>Many personalizations are made to communicate a message to others, but the cell phone home screen is a space unlikely to be seen by many others. Despite this privacy, home screen organization has become an important expressive outlet for many. With a growing industry of highly-customizable digital organization tools that often pitch their necessity on a constant demand for optimization, home screen customization perhaps serves to as a self-affirmation of one’s control and organization. </div><div className={styles.para}>Like intricately-designed Notion pages and the growing popularity (https://business.yougov.com/content/49901-scribbles-and-screens-a-look-at-the-evolving-stationery-market-in-the-uk) of highly-optimized stationary products, a well-organized home screen is a near-constant reminder of one’s sense of control. As our lives are increasingly reflected through the digital platforms we access through our home screens, maintaining its pristine aesthetic might percolate this sense of calm and control to the overwhelming digital world beyond the home screen. </div>",
//         camPos: 1,
//         light: 1,
//         CS_camPos: 1,
//         subtitle: "Convincing ourselves of our own projections",
//         origin: 2000,
//         primary_influences: [],
//     },
    
//   ];